### ISSUE TITLE
Occupy maven central

### ISSUE THREAD

**Issue by zuzunker** [vantuz-subhuman/whakamatautau-util#1]
We need maven access to the tools.
1. Find a repo
2. Configure release\deploy in the POM
3. Release current version and deploy it to the repo

**Comment by zuzunker** [comment]
This manuals were used to fix POM for release:
http://central.sonatype.org/pages/apache-maven.html
http://central.sonatype.org/pages/requirements.html

**Comment by vantuz-subhuman** [comment]
This manual were used to prepare for the release: http://central.sonatype.org/pages/requirements.html

**Comment by zuzunker** [comment]
Closed by mistake

**Comment by zuzunker** [comment]
New project request:
https://issues.sonatype.org/browse/OSSRH-17157

**Comment by zuzunker** [comment]
```
<dependency>
  <groupId>org.whaka</groupId>
  <artifactId>whakamatautau-util</artifactId>
  <version>0.0.7</version>
</dependency>
```
