### ISSUE TITLE
[Utils] Create event collector

### ISSUE THREAD

**Issue by visitorus** [vantuz-subhuman/whakamatautau-util#60]
1. Create collector which will record all arguments from the called method. It should contain filters (Predicate) for the event processing.
2. Create custom filter (extends Predicate) with additional method which will be called when ALL filters will be passed successfully.
# 

**Note:**
1. Collector implementation should use Mockito library to create mocks for intercepted listeners. Therefore collector will create it's own instance of a listener, which then might be received from it and used in actual functionality.
2. The things required to instantiate a collector are
   1. Class<ListenerType> of the intercepted listener.
   2. BiConsumer<ListenerType, EventType> that performs call of the method to be intercepted.
3. Collector should assert that specified `BiConsumer` perform one and only one call to the method ought to be intercepted.
# 

**Codebase:**
1. Implement class `EventCollector<Target, Event>` in the `whaka.mock` package
2. Implement nested interface `EventCollector.EventHandler<Event>`

**Comment by zuzunker** [comment]
Type `EventCollector.EventHandler<Event>` should extend `Predicate<Event>` and implement a single additional method: `void eventCollected(Event e);`

When an event is successfully tested by all predicates specified into an `EventCollector` instance - it shall be "collected" and passed to the `#eventCollected` method of all the specified predicates that are instances of the `EventHandler`.
